server.port=${PORT:3001}

spring.data.mongodb.uri=${MONGODB_URI}
spring.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=false

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.health.rabbit.enabled=false
management.health.mail.enabled=false
management.health.mongo.enabled=false

logging.level.root=WARN
logging.level.ar.edu.unq=INFO