spring.application.name=mitvu
spring.profiles.active=dev
server.port=3001
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=mitvu_db
spring.mongodb.uri=mongodb://localhost:27017/mitvu_db

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#####################################
########## SMTP de Google ###########
#####################################
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.debug=true

#####################################
############### NACHO ###############
#####################################
#spring.mail.username=nachoferro112233@gmail.com
#spring.mail.password=ukaybusropkmxmcs

#####################################
############### ELIAN ###############
#####################################
#spring.mail.username=eliancamiloalejandro@gmail.com
#spring.mail.password=wttedditjxpqavqo


#####################################
########## SMTP de Mailtrap #########
#####################################
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=d69adae76bc85e
spring.mail.password=c5470c0e91cf5d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true